version: '3.8'

services:
  backend:
    image: namithajc/gift-fe
    container_name: gift-be
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    image: namithajc/gift-be
    container_name: gift-fe
    ports:
      - "80:80"
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
